# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:
    branches: [ master ]

env:
  WEB3STORAGE_TOKEN: ${{ secrets.WEB3STORAGE_TOKEN }}

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [16.x, 17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # THIS PART IS INSPIRED BY https://github.com/trufflesuite/ganache/actions/runs/1360710786/workflow
    # TO GET THE CI TO WORK WITH TRUFFLE ON WINDOWS. IT IS COPY PASTED UNTIL...
    - name: Add msbuild to PATH
        # we need msbuild tools for the `bigint-buffer` module
        if: startsWith(matrix.os, 'windows-')
        uses: microsoft/setup-msbuild@v1.0.2

    - name: install node tools
        # we don't need to install the windows-build-tools package, as we
        # already have almost everything we need. We only need to install
        # python 2.7. Also windows-build-tools@4 fails to install because some
        # resources it downloads no longer exist, and windows-build-tools@5
        # fails to install Python (it will wait on the python installer forever)
        if: startsWith(matrix.os, 'windows-')
        uses: actions/setup-python@v2
        with:
          python-version: "2.7"

    - name: install node-gyp
        if: startsWith(matrix.os, 'windows-')
        run: npm install --global node-gyp@7.1.2

    - name: Set node config to use python2.7
        if: startsWith(matrix.os, 'windows-')
        run: npm config set python python2.7

    - name: Set node config to set msvs_version to 2019
        if: startsWith(matrix.os, 'windows-')
        run: npm config set msvs_version 2019 --global
    # ... UNTIL HERE. THE PART BELOW WAS PART OF THE FILE BEFORE. 
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test